### ISSUE TITLE
App crash when trying input special character in ExpiryDateEditText

### ISSUE THREAD

**Issue by nqtsparda** [omise/omise-android#259]
Hi team

I am facing crash issue when inputting asterisk (*) into ExpiryDateEditText, please help to check

Omise version: 4.8.0

Crash log:
`java.lang.NumberFormatException: For input string: "*"
	at java.lang.Integer.parseInt(Integer.java:604)
	at java.lang.Integer.parseInt(Integer.java:650)
	at co.omise.android.ui.ExpiryDateEditText.formatString(SourceFile:1)
	at co.omise.android.ui.ExpiryDateEditText.setExpiryDateText(SourceFile:3)
	at co.omise.android.ui.ExpiryDateEditText.access$setExpiryDateText(SourceFile:1)
	at co.omise.android.ui.ExpiryDateEditText$a.onTextChanged(SourceFile:15)
	at android.widget.TextView.sendOnTextChanged(TextView.java:10961)
	at android.widget.TextView.handleTextChanged(TextView.java:11076)
	at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:14205)
	at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1268)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:577)
	at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:314)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:508)
	at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:304)
	at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:48)
	at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:944)
	at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:219)
	at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:204)
	at android.view.inputmethod.InputConnectionWrapper.commitText(InputConnectionWrapper.java:192)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:572)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:134)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:334)
	at android.app.ActivityThread.main(ActivityThread.java:8513)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)`

**Comment by danfowler** [comment]
Thanks @nqtsparda we'll take a look 👀

**Comment by aashishgurung** [comment]
@nqtsparda We have implemented the fix and will include it in our next release.
