### ISSUE TITLE
How to not open expected result url

### ISSUE THREAD

**Issue by j2emanue** [omise/omise-android#40]
EXTRA_EXPECTED_RETURN_URLSTRING_PATTERNS i set to https://www.mywebsite.com

but the problem is i am using a native app and i do not want to leave the application after i get the authorization call back of either success/failure in the acitivityResult.  I tried setting the EXTRA_EXPECTED_RETURN_URLSTRING_PATTERNS to an empty array but its not helping.  What i want to accomplish is that after the user authenticates your activity then closes and sends me a result code, i'll open a native window depending on that result.  How can i accomplish this ?

when i try to send an empty string for return URL i get the following stack trace error:

```

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equalsIgnoreCase(java.lang.String)' on a null object reference
03-09 03:23:29.990 3196-3196/com.mobile.myapp.labs W/System.err:     at co.omise.android.ui.AuthorizingPaymentActivity$a.a(SourceFile:75)
03-09 03:23:29.990 3196-3196/com.mobile.myapp.labs W/System.err:     at co.omise.android.ui.AuthorizingPaymentActivity$1.shouldOverrideUrlLoading(SourceFile:110)
03-09 03:23:29.990 3196-3196/com.mobile.myapp.labs W/System.err:     at com.android.webview.chromium.WebViewContentsClientAdapter.shouldOverrideUrlLoading(WebViewContentsClientAdapter.java:331)
03-09 03:23:29.990 3196-3196/com.mobile.myapp.labs W/System.err:     at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:265)
03-09 03:23:29.990 3196-3196/com.mobile.myapp.labs W/System.err:     at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
03-09 03:23:29.990 3196-3196/com.mobile.myapp.labs W/System.err:     at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
03-09 03:23:29.990 3196-3196/com.mobile.myapp.labs W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
03-09 03:23:29.990 3196-3196/com.mobile.myapp.labs W/System.err:     at android.os.Looper.loop(Looper.java:148)
03-09 03:23:29.990 3196-3196/com.mobile.myapp.labs W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
03-09 03:23:29.990 3196-3196/com.mobile.myapp.labs W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
03-09 03:23:29.990 3196-3196/com.mobile.myapp.labs W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-09 03:23:29.990 3196-3196/com.mobile.myapp.labs W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by j2emanue** [comment]
after i actually caught the activityResult it allows me to handle the URL myself.  this works. closing issue.

**Comment by nuxzero** [comment]
@j2emanue Do you still have any issues? If not, I'm going to close this issue.

**Comment by j2emanue** [comment]
Close it. Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
